project:
  machine_name: imp-public
  prefix: IMPW
  human_name: 'Incident Management Portal - Website'
  profile:
    name: lightning
  local:
    protocol: http
    hostname: 'local.${project.machine_name}.com'
git:
  default_branch: master
  remotes:
    pantheon: 'ssh://codeserver.dev.2b65110f-c371-4713-b76d-e1a2332761a5@codeserver.dev.2b65110f-c371-4713-b76d-e1a2332761a5.drush.in:2222/~/repository.git'
drush:
  aliases:
    remote: 'pantheon.${project.machine_name}.dev'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: [acsf, acquia_connector, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
  prod:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
target-hooks:
  frontend-setup:
    dir: ${docroot}/themes/particle
    command: 'npm install'
  frontend-build:
    dir: ${docroot}/themes/particle
    command: 'npm run build:drupal'
